version: '3.8'

services:
  ruby:
    build:
      context: .
      dockerfile: Dockerfile.ruby
    container_name: ruby-container
    volumes:
      - ruby-data:/usr/src/app
    working_dir: /usr/src/app/workspace
    stdin_open: true
    tty: true
    mem_limit: 512m

  vscode:
    build:
      context: .
      dockerfile: Dockerfile.vscode
    container_name: vscode-container
    ports:
      - "8080:8080"
    volumes:
      - ruby-data:/home/workspace
    working_dir: /home/workspace
    mem_limit: 512m

volumes:
  ruby-data:

